//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARACLAR
    {
        public int AracID { get; set; }
        public Nullable<int> Marka { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> UretımYılı { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> YakıtTıpı { get; set; }
        public string FOTO { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLMARKA TBLMARKA { get; set; }
        public virtual TBLYAKIT TBLYAKIT { get; set; }
    }
}
