//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGELIR
    {
        public int GelırID { get; set; }
        public string GelirTuru { get; set; }
        public Nullable<decimal> GelirTutarı { get; set; }
        public Nullable<System.DateTime> GelirTarıh { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string Acıklama { get; set; }
    }
}
