//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGIDER
    {
        public int GıderID { get; set; }
        public string GiderTuru { get; set; }
        public Nullable<decimal> GıderTutarı { get; set; }
        public Nullable<System.DateTime> GelirTarih { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string Açıklama { get; set; }
    }
}
