//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONELODEME
    {
        public int OdemeID { get; set; }
        public Nullable<int> OdemeTuru { get; set; }
        public string OdemeTutarı { get; set; }
        public Nullable<int> OdenenKısı { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<System.DateTime> Tarh { get; set; }
    
        public virtual TBLODEMEBICIM TBLODEMEBICIM { get; set; }
        public virtual TBLODEMEBICIM TBLODEMEBICIM1 { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
