//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSODEME
    {
        public int PersOdemeID { get; set; }
        public Nullable<int> TUR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> ODENEN { get; set; }
        public Nullable<int> PEDID { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLODEMEBICIM TBLODEMEBICIM { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
