//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIRKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSIRKET()
        {
            this.TBLÇEKSENET = new HashSet<TBLÇEKSENET>();
            this.TBLFIRMAHAREKETLERI = new HashSet<TBLFIRMAHAREKETLERI>();
        }
    
        public int SırkID { get; set; }
        public string SırkTC { get; set; }
        public string SırkAd { get; set; }
        public string SırkUnvan { get; set; }
        public string SırkTelefon { get; set; }
        public string SırkAdres { get; set; }
        public string SırkVergı { get; set; }
        public Nullable<bool> SırketTıp { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string FOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLÇEKSENET> TBLÇEKSENET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFIRMAHAREKETLERI> TBLFIRMAHAREKETLERI { get; set; }
    }
}
