//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraçKiralama2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLÇEKSENET
    {
        public int CekID { get; set; }
        public Nullable<int> ÇekTür { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> OdemeTarih { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public string Tutar { get; set; }
        public string Durum { get; set; }
        public string Açıklama { get; set; }
        public Nullable<bool> DURUM1 { get; set; }
    
        public virtual TBLODEMEBICIM TBLODEMEBICIM { get; set; }
        public virtual TBLSIRKET TBLSIRKET { get; set; }
    }
}
